export const artIcons = [
  "camera-outline",
  "image-outline",
  "videocam-outline",
  "musical-notes-outline",
  "color-palette-outline",
  "flask-outline",
  "bag-handle-outline",
  "cut-outline",
  "desktop-outline",
  "telescope-outline",
  "extension-puzzle-outline",
  "brush-outline",
  "calendar-outline",
  "ticket-outline",
];
export const sportsIcons = [
  "pulse-outline",
  "bicycle-outline",
  "american-football-outline",
  "basketball-outline",
  "ribbon-outline",
  "tennisball-outline",
  "boat-outline",
  "bowling-ball-outline",
  "map-outline",
  "print-outline",
  "barbell-outline",
  "shirt-outline",
  "trophy-outline",
];
export const foodsIcons = [
  "nutrition-outline",
  "fast-food-outline",
  "cafe-outline",
  "fish-outline",
  "scale-outline",
  "pizza-outline",
  "beer-outline",
  "restaurant-outline",
  "ice-cream-outline",
];
export const financialIcons = [
  "shield-checkmark-outline",
  "analytics-outline",
  "card-outline",
  "wallet-outline",
  "earth-outline",
  "laptop-outline",
  "phone-portrait-outline",
  "newspaper-outline",
  "infinite-outline",
  "server-outline",
  "school-outline",
];
export const activityIcons = [
  "storefront-outline",
  "subway-outline",
  "easel-outline",
  "airplane-outline",
  "mail-outline",
  "snow-outline",
  "library-outline",
  "car-sport-outline",
  "calculator-outline",
  "construct-outline",
  "game-controller-outline",
  "bulb-outline",
  "alarm-outline",
  "leaf-outline",
  "bed-outline",
  "bar-chart-outline",
  "call-outline",
  "bus-outline",
  "chatbox-ellipses-outline",
  "code-slash-outline",
  "mic-outline",
  "rainy-outline",
];

export const iconsTray = [
  {
    title: "Sports",
    icons: sportsIcons,
  },
  {
    title: "Arts & Design",
    icons: artIcons,
  },
  {
    title: "Foods & Beverage",
    icons: foodsIcons,
  },
  {
    title: "Finance",
    icons: financialIcons,
  },
];
